### ISSUE TITLE
Not toLowerCase

### ISSUE THREAD

**Issue by trantienz** [jonmalave/jSearch#1]
Hello,

I'm using jSearch on my site, but in my data-type, alway a name with Capitalize Case like this : **New York** not  **new york**.

jSearch work when data-type is lower case but my CMS not allow to convert to lower case like this. Please help.

**Comment by jonmalave** [comment]
@trantienz what CMS are you using? why are you unable to set all data-types to lowercase, this would be the best way to define your data type. This way whenever a user inputs a search, it does not matter how they type the characters, it will convert to lowercase to match the lowercase data-type.
